name: Deploy Infrastructure

on:
  workflow_dispatch:
  #repository_dispatch:
env:
  tf_version: 'latest'
  tf_working_dir: './terraform'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@master

      - name: Set GCP environment
        run: echo ::set-env name=BRANCH_NAME::$(echo ${GITHUB_BASE_REF#refs/heads/})
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: set GCP project
        run: gcloud config set project ${{ secrets.PROJECT_NAME }}

      - name: "Terraform Init"
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: environments/${{ env.BRANCH_NAME }}
          tf_actions_subcommand: init
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}

      - name: "Terraform Plan"
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: environments/${{ env.BRANCH_NAME }}
          tf_actions_subcommand: plan
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}
          
      - name: "Terraform Apply"
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: environments/${{ env.BRANCH_NAME }}
          tf_actions_subcommand: apply
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}